version: 2
models:
  - name: confirmed_count_by_country_yesterday
    columns:
      - name: country_name
        tests:
          - unique
          - not_null
      - name: confirmed_count
        tests:
          - not_null
      - name: date
        tests:
          - not_null
